name: Dump GitHub Context

on: [ push, pull_request ]

jobs:
  dump:
    name: Dump GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
